### ISSUE TITLE
KeyError: 'chr1_89476615_89476806'

### ISSUE THREAD

**Issue by gnilihzeux** [Kevinzjy/CIRIquant#17]
Dear author,
   As the title, I have no idea about the reason. More information is

```
#####]
[Fri 2020-11-13 08:13:25] [INFO ] Building circular index ..
[Fri 2020-11-13 08:13:26] [INFO ] De novo alignment for circular RNAs ..
[Fri 2020-11-13 08:25:47] [INFO ] Detecting reads containing Back-splicing signa                                                                  ls
Traceback (most recent call last):
  File "/root/miniconda2/bin/CIRIquant", line 11, in <module>
    load_entry_point('CIRIquant==1.1.1', 'console_scripts', 'CIRIquant')()
  File "/root/miniconda2/lib/python2.7/site-packages/CIRIquant-1.1.1-py2.7.egg/C                                                                  IRIquant/main.py", line 183, in main
    out_file = circ.proc(log_file, thread, bed_file, hisat_bam, rnaser_file, rea                                                                  ds, outdir, prefix, anchor, lib_type)
  File "/root/miniconda2/lib/python2.7/site-packages/CIRIquant-1.1.1-py2.7.egg/C                                                                  IRIquant/circ.py", line 655, in proc
    cand_bsj = proc_denovo_bam(denovo_bam, thread, circ_info, anchor, lib_type)
  File "/root/miniconda2/lib/python2.7/site-packages/CIRIquant-1.1.1-py2.7.egg/C                                                                  IRIquant/circ.py", line 320, in proc_denovo_bam
    tmp_cand = job.get()
  File "/root/miniconda2/lib/python2.7/multiprocessing/pool.py", line 572, in ge                                                                  t
    raise self._value
KeyError: 'chr1_89476615_89476806'
```
  My bed format is:
```
chr1    541981  542012  chr1_541981_542012      0       +
chr1    6880241 6885270 chr1_6880241_6885270    0       +
chr1    8716032 8716500 chr1_8716032_8716500    0       -
```
   Wish your reply.
   Thanks.

**Comment by Kevinzjy** [comment]
Hi @gnilihzeux , could you try renaming all circRNAs to format like "chr1:541981|542012" in your bed file, and run CIRIquant again? I believe this will fix the problem.

**Comment by gnilihzeux** [comment]
OK, I'll try & reply later.

**Comment by gnilihzeux** [comment]
Yes, you're right.
