### ISSUE TITLE
change the permissions on 'CIRI2.pl' while running CIRIquant on cluster

### ISSUE THREAD

**Issue by MaryamLabaf** [Kevinzjy/CIRIquant#36]
Hello,

I m trying to run CIRIquant on cluster but I get the error message for CIRI2.pl permission. CIRIquant installed using condo on cluster. 
Here is the error message. 
[ml98b@ghpcc06 2_S2]$ source /share/pkg/condas/2018-05-11/bin/activate && conda activate CIRIquant_1.1.2
(CIRIquant_1.1.2) [ml98b@ghpcc06 2_S2]$ CIRIquant -t 4 -1 ./data/circRNA_fastq_files/2_S2_L001_R1_001.fastq.gz -2 ./data/circRNA_fastq_files/2_S2_L001_R2_001.fastq.gz --config ./dmel_ENS_BDGP6.yml -p 2_S2
Traceback (most recent call last):
  File "/share/pkg/condas/2018-05-11/envs/CIRIquant_1.1.2/bin/CIRIquant", line 8, in <module>
    sys.exit(main())
  File "/share/pkg/condas/2018-05-11/envs/CIRIquant_1.1.2/lib/python2.7/site-packages/CIRIquant/main.py", line 126, in main
    os.chmod(lib_path + '/CIRI2.pl', 0o755)
OSError: [Errno 13] Permission denied: '/share/pkg/conda/2018-05-11/envs/CIRIquant_1.1.2/lib/python2.7/site-packages/libs/CIRI2.pl'

**Comment by Kevinzjy** [comment]
Hi @MaryamLabaf , CIRIquant uses the "chmod" command to ensure CIRI2.pl is executable, while your account does not have permission to edit the public file '/share/pkg/conda/2018-05-11/envs/CIRIquant_1.1.2/lib/python2.7/site-packages/libs/CIRI2.pl'. 

Thus, you have to install CIRIquant under your own directory, so you can have full access to the CIRI2.pl.

**Comment by MaryamLabaf** [comment]
Hi @Kevinzjy, Thank you for your reply. To install the CIRIquant using the condo, it seems the hisat2 version is 2.2.0. It is possible to modify the .yml file with the higher version of hisat2?

**Comment by Kevinzjy** [comment]
> 

That's ok, CIRIquant does not require a specific hisat2 version.
