### ISSUE TITLE
Hisat2 produces empty bam files

### ISSUE THREAD

**Issue by Braulium** [Kevinzjy/CIRIquant#63]
Dear CIRIquant team,

I am trying to use CIRIquant to discover and quantify circRNAs in PE eCLIP datasets. 

Everytime the software uses Hisat internally, it produces an empty bam and bam.bai file. 
If I only provide fastq files, then the execution stops inmediately after HISAT2 alignment. 
If I provide BAM files, execution stops after generating NAME_denovo.sorted.bam with the following error in the stderr:

[Tue 2024-02-13 15:04:52] [DEBUG] De-novo bam: /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/04_CIRIquant_output/circ/eCLIP_rep1_denovo.sorted.bam
[Tue 2024-02-13 15:04:52] [INFO ] Detecting reads containing Back-splicing signals
Traceback (most recent call last):
  File "/scicore/home/scheiffe/ortiz0000/softwares/CIRIquant/CIRIquant_env/bin/CIRIquant", line 8, in <module>
    sys.exit(main())
  File "/scicore/home/scheiffe/ortiz0000/softwares/CIRIquant/CIRIquant_env/lib/python2.7/site-packages/CIRIquant/main.py", line 198, in main
    args.no_fsj, args.bsj_read_file)
  File "/scicore/home/scheiffe/ortiz0000/softwares/CIRIquant/CIRIquant_env/lib/python2.7/site-packages/CIRIquant/circ.py", line 658, in proc
    cand_bsj = proc_denovo_bam(denovo_bam, thread, circ_info, anchor, lib_type)
  File "/scicore/home/scheiffe/ortiz0000/softwares/CIRIquant/CIRIquant_env/lib/python2.7/site-packages/CIRIquant/circ.py", line 306, in proc_denovo_bam
    sam = pysam.AlignmentFile(bam_file, 'rb')
  File "pysam/libcalignmentfile.pyx", line 736, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 985, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

And the following in the log file:
Error: Encountered internal HISAT2 exception (#1)
Command: /scicore/home/scheiffe/ortiz0000/softwares/CIRIquant/CIRIquant_env/bin/hisat2-align-s --wrapper basic-0 -p 4 --dta -q -x /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/04_CIRIquant_output/circ/eCLIP_rep1_index --read-lengths 66,65,64,63,62,40,33,39,41,37,44,32,56,31,38,35,46,60,34,61,47,42,54,45,57,36,58,49,30,51,24,55,59,50,52,53,48,27,43,26,23,29,25,28,22,19,18,21,20 -1 /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/03_adapters_trimmed/eIF3GHA_eCLIP_rep1_R2_UMIout.RmAdap4x.fastq -2 /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/03_adapters_trimmed/eIF3GHA_eCLIP_rep1_R1_UMIout.RmAdap4x.fastq
(ERR): hisat2-align exited with value 1
[Tue 2024-02-13 15:04:47] [DEBUG] /scicore/home/scheiffe/ortiz0000/softwares/CIRIquant/CIRIquant_env/bin/samtools sort --threads 4 -o /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/04_CIRIquant_output/circ/eCLIP_rep1_denovo.sorted.bam /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/04_CIRIquant_output/circ/eCLIP_rep1_denovo.bam
[Tue 2024-02-13 15:04:47] [DEBUG] /scicore/home/scheiffe/ortiz0000/softwares/CIRIquant/CIRIquant_env/bin/samtools index -@ 4 /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/04_CIRIquant_output/circ/eCLIP_rep1_denovo.sorted.bam
[Tue 2024-02-13 15:04:52] [DEBUG] De-novo bam: /scicore/home/scheiffe/ortiz0000/eIF3g_project/circRNAs/eCLIP_eIF3g_HA/04_CIRIquant_output/circ/eCLIP_rep1_denovo.sorted.bam
[Tue 2024-02-13 15:04:52] [INFO ] Detecting reads containing Back-splicing signals

I have checked my hisat2 index and used it for aligning my fastq files independently using HISAT2, so I know botjh fastq and index are OK.

Any idea why this may be happening? Any help would be appreciated.
Many thanks.

Best regards,
Raul

**Comment by Helena-Zancanaro** [comment]
Dear Raul,

I am experiencing exactly the same issue you described and wanted to ask whether you were able to solve it, and if so, how.

In my case, I am not sure whether the problem could be related to running CIRIquant in parallel for multiple samples. I have noticed that when I run my pipeline processing one sample at a time, this error does not occur, whereas it consistently appears when I run several samples in parallel.

I would really appreciate it if you could share any insights or solutions you may have found.

Thank you in advance for your help.

Best regards,
Helena
